// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Microsoft.Test.DataServices
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "DotNetWebServiceSoap", Namespace = "http://Avalon/Test/ConnectedData")]
    public partial class DotNetWebService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback _getStoreNameOperationCompleted;

        private System.Threading.SendOrPostCallback _mirrorStringOperationCompleted;

        private System.Threading.SendOrPostCallback _getTopAuthorsOperationCompleted;

        private System.Threading.SendOrPostCallback _getTopAuthors1OperationCompleted;

        private System.Threading.SendOrPostCallback _getAuthorsOperationCompleted;

        private System.Threading.SendOrPostCallback _getTopAuthors2OperationCompleted;

        private System.Threading.SendOrPostCallback _convertTemperatureOperationCompleted;

        private System.Threading.SendOrPostCallback _getBookOperationCompleted;

        private System.Threading.SendOrPostCallback _getBook1OperationCompleted;

        private System.Threading.SendOrPostCallback _getBooksByAuthorOperationCompleted;

        private System.Threading.SendOrPostCallback _getTotalOperationCompleted;

        private System.Threading.SendOrPostCallback _getInventoryCountOperationCompleted;

        /// <remarks/>
        public DotNetWebService()
        {
            this.Url = "http://avalondata/DotnetWebservice/DotNetWebService.asmx";
        }

        /// <remarks/>
        public event GetStoreNameCompletedEventHandler GetStoreNameCompleted;

        /// <remarks/>
        public event MirrorStringCompletedEventHandler MirrorStringCompleted;

        /// <remarks/>
        public event GetTopAuthorsCompletedEventHandler GetTopAuthorsCompleted;

        /// <remarks/>
        public event GetTopAuthors1CompletedEventHandler GetTopAuthors1Completed;

        /// <remarks/>
        public event GetAuthorsCompletedEventHandler GetAuthorsCompleted;

        /// <remarks/>
        public event GetTopAuthors2CompletedEventHandler GetTopAuthors2Completed;

        /// <remarks/>
        public event ConvertTemperatureCompletedEventHandler ConvertTemperatureCompleted;

        /// <remarks/>
        public event GetBookCompletedEventHandler GetBookCompleted;

        /// <remarks/>
        public event GetBook1CompletedEventHandler GetBook1Completed;

        /// <remarks/>
        public event GetBooksByAuthorCompletedEventHandler GetBooksByAuthorCompleted;

        /// <remarks/>
        public event GetTotalCompletedEventHandler GetTotalCompleted;

        /// <remarks/>
        public event GetInventoryCountCompletedEventHandler GetInventoryCountCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/GetStoreName", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStoreName()
        {
            object[] results = this.Invoke("GetStoreName", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetStoreName(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetStoreName", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndGetStoreName(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetStoreNameAsync()
        {
            this.GetStoreNameAsync(null);
        }

        /// <remarks/>
        public void GetStoreNameAsync(object userState)
        {
            if ((this._getStoreNameOperationCompleted == null))
            {
                this._getStoreNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoreNameOperationCompleted);
            }
            this.InvokeAsync("GetStoreName", new object[0], this._getStoreNameOperationCompleted, userState);
        }

        private void OnGetStoreNameOperationCompleted(object arg)
        {
            if ((this.GetStoreNameCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoreNameCompleted(this, new GetStoreNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/MirrorString", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MirrorString(string strIn)
        {
            object[] results = this.Invoke("MirrorString", new object[] {
                        strIn});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginMirrorString(string strIn, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("MirrorString", new object[] {
                        strIn}, callback, asyncState);
        }

        /// <remarks/>
        public string EndMirrorString(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void MirrorStringAsync(string strIn)
        {
            this.MirrorStringAsync(strIn, null);
        }

        /// <remarks/>
        public void MirrorStringAsync(string strIn, object userState)
        {
            if ((this._mirrorStringOperationCompleted == null))
            {
                this._mirrorStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMirrorStringOperationCompleted);
            }
            this.InvokeAsync("MirrorString", new object[] {
                        strIn}, this._mirrorStringOperationCompleted, userState);
        }

        private void OnMirrorStringOperationCompleted(object arg)
        {
            if ((this.MirrorStringCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MirrorStringCompleted(this, new MirrorStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/Top 10", RequestElementName = "Top 10", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseElementName = "Top 10Response", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Top_x0020_10Result")]
        public string[] GetTopAuthors()
        {
            object[] results = this.Invoke("GetTopAuthors", new object[0]);
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetTopAuthors(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetTopAuthors", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string[] EndGetTopAuthors(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public void GetTopAuthorsAsync()
        {
            this.GetTopAuthorsAsync(null);
        }

        /// <remarks/>
        public void GetTopAuthorsAsync(object userState)
        {
            if ((this._getTopAuthorsOperationCompleted == null))
            {
                this._getTopAuthorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopAuthorsOperationCompleted);
            }
            this.InvokeAsync("GetTopAuthors", new object[0], this._getTopAuthorsOperationCompleted, userState);
        }

        private void OnGetTopAuthorsOperationCompleted(object arg)
        {
            if ((this.GetTopAuthorsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopAuthorsCompleted(this, new GetTopAuthorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName = "GetTopAuthors1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/Top X", RequestElementName = "Top X", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseElementName = "Top XResponse", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Top_x0020_XResult")]
        public string[] GetTopAuthors(int to)
        {
            object[] results = this.Invoke("GetTopAuthors1", new object[] {
                        to});
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetTopAuthors1(int to, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetTopAuthors1", new object[] {
                        to}, callback, asyncState);
        }

        /// <remarks/>
        public string[] EndGetTopAuthors1(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public void GetTopAuthors1Async(int to)
        {
            this.GetTopAuthors1Async(to, null);
        }

        /// <remarks/>
        public void GetTopAuthors1Async(int to, object userState)
        {
            if ((this._getTopAuthors1OperationCompleted == null))
            {
                this._getTopAuthors1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopAuthors1OperationCompleted);
            }
            this.InvokeAsync("GetTopAuthors1", new object[] {
                        to}, this._getTopAuthors1OperationCompleted, userState);
        }

        private void OnGetTopAuthors1OperationCompleted(object arg)
        {
            if ((this.GetTopAuthors1Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopAuthors1Completed(this, new GetTopAuthors1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/List of Authors from specified point to specifie" +
            "d point", RequestElementName = "List of Authors from specified point to specified point", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseElementName = "List of Authors from specified point to specified pointResponse", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("List_x0020_of_x0020_Authors_x0020_from_x0020_specified_x0020_point_x0020_to_x0020" +
            "_specified_x0020_pointResult")]
        public string[] GetAuthors(int from, int to)
        {
            object[] results = this.Invoke("GetAuthors", new object[] {
                        from,
                        to});
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAuthors(int from, int to, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAuthors", new object[] {
                        from,
                        to}, callback, asyncState);
        }

        /// <remarks/>
        public string[] EndGetAuthors(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public void GetAuthorsAsync(int from, int to)
        {
            this.GetAuthorsAsync(from, to, null);
        }

        /// <remarks/>
        public void GetAuthorsAsync(int from, int to, object userState)
        {
            if ((this._getAuthorsOperationCompleted == null))
            {
                this._getAuthorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorsOperationCompleted);
            }
            this.InvokeAsync("GetAuthors", new object[] {
                        from,
                        to}, this._getAuthorsOperationCompleted, userState);
        }

        private void OnGetAuthorsOperationCompleted(object arg)
        {
            if ((this.GetAuthorsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthorsCompleted(this, new GetAuthorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName = "GetTopAuthors2")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/Get Count", RequestElementName = "Get Count", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseElementName = "Get CountResponse", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Get CountResult")]
        public int GetTopAuthors(string[] list)
        {
            object[] results = this.Invoke("GetTopAuthors2", new object[] {
                        list});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetTopAuthors2(string[] list, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetTopAuthors2", new object[] {
                        list}, callback, asyncState);
        }

        /// <remarks/>
        public int EndGetTopAuthors2(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void GetTopAuthors2Async(string[] list)
        {
            this.GetTopAuthors2Async(list, null);
        }

        /// <remarks/>
        public void GetTopAuthors2Async(string[] list, object userState)
        {
            if ((this._getTopAuthors2OperationCompleted == null))
            {
                this._getTopAuthors2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopAuthors2OperationCompleted);
            }
            this.InvokeAsync("GetTopAuthors2", new object[] {
                        list}, this._getTopAuthors2OperationCompleted, userState);
        }

        private void OnGetTopAuthors2OperationCompleted(object arg)
        {
            if ((this.GetTopAuthors2Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopAuthors2Completed(this, new GetTopAuthors2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/ConvertTemperature", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double ConvertTemperature(double dFahrenheit)
        {
            object[] results = this.Invoke("ConvertTemperature", new object[] {
                        dFahrenheit});
            return ((double)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConvertTemperature(double dFahrenheit, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConvertTemperature", new object[] {
                        dFahrenheit}, callback, asyncState);
        }

        /// <remarks/>
        public double EndConvertTemperature(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((double)(results[0]));
        }

        /// <remarks/>
        public void ConvertTemperatureAsync(double dFahrenheit)
        {
            this.ConvertTemperatureAsync(dFahrenheit, null);
        }

        /// <remarks/>
        public void ConvertTemperatureAsync(double dFahrenheit, object userState)
        {
            if ((this._convertTemperatureOperationCompleted == null))
            {
                this._convertTemperatureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertTemperatureOperationCompleted);
            }
            this.InvokeAsync("ConvertTemperature", new object[] {
                        dFahrenheit}, this._convertTemperatureOperationCompleted, userState);
        }

        private void OnConvertTemperatureOperationCompleted(object arg)
        {
            if ((this.ConvertTemperatureCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertTemperatureCompleted(this, new ConvertTemperatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/Get a book", RequestElementName = "Get a book", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseElementName = "Get a bookResponse", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Get a bookResult")]
        public DotNetBook GetBook()
        {
            object[] results = this.Invoke("GetBook", new object[0]);
            return ((DotNetBook)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetBook(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetBook", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public DotNetBook EndGetBook(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DotNetBook)(results[0]));
        }

        /// <remarks/>
        public void GetBookAsync()
        {
            this.GetBookAsync(null);
        }

        /// <remarks/>
        public void GetBookAsync(object userState)
        {
            if ((this._getBookOperationCompleted == null))
            {
                this._getBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookOperationCompleted);
            }
            this.InvokeAsync("GetBook", new object[0], this._getBookOperationCompleted, userState);
        }

        private void OnGetBookOperationCompleted(object arg)
        {
            if ((this.GetBookCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookCompleted(this, new GetBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName = "GetBook1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/Get specified book", RequestElementName = "Get specified book", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseElementName = "Get specified bookResponse", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Get specified bookResult")]
        public DotNetBook GetBook(string title)
        {
            object[] results = this.Invoke("GetBook1", new object[] {
                        title});
            return ((DotNetBook)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetBook1(string title, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetBook1", new object[] {
                        title}, callback, asyncState);
        }

        /// <remarks/>
        public DotNetBook EndGetBook1(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DotNetBook)(results[0]));
        }

        /// <remarks/>
        public void GetBook1Async(string title)
        {
            this.GetBook1Async(title, null);
        }

        /// <remarks/>
        public void GetBook1Async(string title, object userState)
        {
            if ((this._getBook1OperationCompleted == null))
            {
                this._getBook1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBook1OperationCompleted);
            }
            this.InvokeAsync("GetBook1", new object[] {
                        title}, this._getBook1OperationCompleted, userState);
        }

        private void OnGetBook1OperationCompleted(object arg)
        {
            if ((this.GetBook1Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBook1Completed(this, new GetBook1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/GetBooksByAuthor", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DotNetBook[] GetBooksByAuthor(string author)
        {
            object[] results = this.Invoke("GetBooksByAuthor", new object[] {
                        author});
            return ((DotNetBook[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetBooksByAuthor(string author, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetBooksByAuthor", new object[] {
                        author}, callback, asyncState);
        }

        /// <remarks/>
        public DotNetBook[] EndGetBooksByAuthor(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DotNetBook[])(results[0]));
        }

        /// <remarks/>
        public void GetBooksByAuthorAsync(string author)
        {
            this.GetBooksByAuthorAsync(author, null);
        }

        /// <remarks/>
        public void GetBooksByAuthorAsync(string author, object userState)
        {
            if ((this._getBooksByAuthorOperationCompleted == null))
            {
                this._getBooksByAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBooksByAuthorOperationCompleted);
            }
            this.InvokeAsync("GetBooksByAuthor", new object[] {
                        author}, this._getBooksByAuthorOperationCompleted, userState);
        }

        private void OnGetBooksByAuthorOperationCompleted(object arg)
        {
            if ((this.GetBooksByAuthorCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBooksByAuthorCompleted(this, new GetBooksByAuthorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/GetTotal", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double GetTotal(DotNetBook[] books)
        {
            object[] results = this.Invoke("GetTotal", new object[] {
                        books});
            return ((double)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetTotal(DotNetBook[] books, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetTotal", new object[] {
                        books}, callback, asyncState);
        }

        /// <remarks/>
        public double EndGetTotal(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((double)(results[0]));
        }

        /// <remarks/>
        public void GetTotalAsync(DotNetBook[] books)
        {
            this.GetTotalAsync(books, null);
        }

        /// <remarks/>
        public void GetTotalAsync(DotNetBook[] books, object userState)
        {
            if ((this._getTotalOperationCompleted == null))
            {
                this._getTotalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTotalOperationCompleted);
            }
            this.InvokeAsync("GetTotal", new object[] {
                        books}, this._getTotalOperationCompleted, userState);
        }

        private void OnGetTotalOperationCompleted(object arg)
        {
            if ((this.GetTotalCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTotalCompleted(this, new GetTotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Avalon/Test/ConnectedData/GetInventoryCount", RequestNamespace = "http://Avalon/Test/ConnectedData", ResponseNamespace = "http://Avalon/Test/ConnectedData", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetInventoryCount(DotNetBook book)
        {
            object[] results = this.Invoke("GetInventoryCount", new object[] {
                        book});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetInventoryCount(DotNetBook book, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetInventoryCount", new object[] {
                        book}, callback, asyncState);
        }

        /// <remarks/>
        public int EndGetInventoryCount(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void GetInventoryCountAsync(DotNetBook book)
        {
            this.GetInventoryCountAsync(book, null);
        }

        /// <remarks/>
        public void GetInventoryCountAsync(DotNetBook book, object userState)
        {
            if ((this._getInventoryCountOperationCompleted == null))
            {
                this._getInventoryCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInventoryCountOperationCompleted);
            }
            this.InvokeAsync("GetInventoryCount", new object[] {
                        book}, this._getInventoryCountOperationCompleted, userState);
        }

        private void OnGetInventoryCountOperationCompleted(object arg)
        {
            if ((this.GetInventoryCountCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInventoryCountCompleted(this, new GetInventoryCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Avalon/Test/ConnectedData")]
    public partial class DotNetBook
    {

        private string _titleField;

        private string _authorField;

        private double _priceField;

        /// <remarks/>
        public string Title
        {
            get
            {
                return this._titleField;
            }
            set
            {
                this._titleField = value;
            }
        }

        /// <remarks/>
        public string Author
        {
            get
            {
                return this._authorField;
            }
            set
            {
                this._authorField = value;
            }
        }

        /// <remarks/>
        public double Price
        {
            get
            {
                return this._priceField;
            }
            set
            {
                this._priceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetStoreNameCompletedEventHandler(object sender, GetStoreNameCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoreNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal GetStoreNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void MirrorStringCompletedEventHandler(object sender, MirrorStringCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MirrorStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal MirrorStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetTopAuthorsCompletedEventHandler(object sender, GetTopAuthorsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopAuthorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal GetTopAuthorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public string[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetTopAuthors1CompletedEventHandler(object sender, GetTopAuthors1CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopAuthors1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal GetTopAuthors1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public string[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetAuthorsCompletedEventHandler(object sender, GetAuthorsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal GetAuthorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public string[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetTopAuthors2CompletedEventHandler(object sender, GetTopAuthors2CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopAuthors2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal GetTopAuthors2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ConvertTemperatureCompletedEventHandler(object sender, ConvertTemperatureCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertTemperatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal ConvertTemperatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public double Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((double)(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetBookCompletedEventHandler(object sender, GetBookCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal GetBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public DotNetBook Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DotNetBook)(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetBook1CompletedEventHandler(object sender, GetBook1CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBook1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal GetBook1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public DotNetBook Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DotNetBook)(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetBooksByAuthorCompletedEventHandler(object sender, GetBooksByAuthorCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBooksByAuthorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal GetBooksByAuthorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public DotNetBook[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DotNetBook[])(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetTotalCompletedEventHandler(object sender, GetTotalCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal GetTotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public double Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((double)(this._results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetInventoryCountCompletedEventHandler(object sender, GetInventoryCountCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInventoryCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] _results;

        internal GetInventoryCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this._results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this._results[0]));
            }
        }
    }
}
