//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamlPadEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamlPadEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] unzip {
            get {
                object obj = ResourceManager.GetObject("unzip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon XamlEdit {
            get {
                object obj = ResourceManager.GetObject("XamlEdit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xamlEditScreen {
            get {
                object obj = ResourceManager.GetObject("xamlEditScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Snippets&gt;
        ///  &lt;Category Name=&quot;Simple Styles&quot; &gt;
        ///    &lt;Snippet Name=&quot;Shared Brushes&quot;&gt;&lt;![CDATA[  &lt;!-- Normal Brush --&gt;
        ///
        ///  &lt;LinearGradientBrush x:Key=&quot;NormalBrush&quot; StartPoint=&quot;0,0&quot; EndPoint=&quot;0,1&quot;&gt;
        ///    &lt;GradientBrush.GradientStops&gt;
        ///      &lt;GradientStopCollection&gt;
        ///        &lt;GradientStop Color=&quot;#FFF&quot; Offset=&quot;0.0&quot;/&gt;
        ///        &lt;GradientStop Color=&quot;#CCC&quot; Offset=&quot;1.0&quot;/&gt;
        ///      &lt;/GradientStopCollection&gt;
        ///    &lt;/GradientBrush.GradientStops&gt;
        ///  &lt;/LinearGradientBrush&gt;
        ///
        ///  &lt;LinearG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XamlSnippets {
            get {
                return ResourceManager.GetString("XamlSnippets", resourceCulture);
            }
        }
        
        internal static byte[] zipResource {
            get {
                object obj = ResourceManager.GetObject("zipResource", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
