import "oaidl.idl";
import "ocidl.idl";
import "mileffects.idl";

interface IMILBitmapEffectPrimitive;

[
    uuid(D2A39CFE-8727-44CB-BAB2-133CB7B8CD9D),
    version(1.0),
    helpstring("effectlib 1.0 Type Library")
]
library effectlib
{
    importlib("stdole2.tlb");
    [
        uuid(C9308B90-2011-47E6-BC3E-872B1AEF7258),
        helpstring("Explode Class")
    ]
    coclass Explode
    {
        [default] interface IMILBitmapEffectPrimitive;
    };
};
