// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// DO NOT Edit this file w/o consulting with the Avalon Build (mailto:ablds) 
// 
using System;
using Avalon.Test.CoreUI.Trusted;
using Avalon.Test.CoreUI;


namespace MS.Utility 
{ 
    internal class RefAssembly 
    { 
        internal const string Version = Microsoft.Internal.BuildInfo.WCP_VERSION; 
        internal const string FileVersion = "6.0.4023.30521"; 
        internal const string PublicKey = Microsoft.Internal.BuildInfo.WCP_PUBLIC_KEY_TOKEN; //Microsoft.Internal.BuildInfo.WCP_PUBLIC_KEY_TOKEN; 
    } 
} 

