// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.311
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>

namespace StyleSnooper.Properties
{
    public partial class Settings : System.Configuration.ApplicationSettingsBase
    {
        private static Settings s_value;

        private static object s_syncObject = new object();

        public static Settings Value
        {
            get
            {
                if ((Settings.s_value == null))
                {
                    System.Threading.Monitor.Enter(Settings.s_syncObject);
                    if ((Settings.s_value == null))
                    {
                        try
                        {
                            Settings.s_value = new Settings();
                        }
                        finally
                        {
                            System.Threading.Monitor.Exit(Settings.s_syncObject);
                        }
                    }
                }
                return Settings.s_value;
            }
        }
    }
}
