#ifndef __codepoint_
#define __codepoint_

//CPT_SEGMET_NAME: 
//CodePoint Segemet.ID various segements in Unicode Table
enum CPT_SEGMENT_NAME
{
    //ENG
    C0_CONTROL = 0,
	LATIN_SIGN1 = 1,
	LATIN_SIGN2 = 2,
	LATIN_SIGN3 = 3,
	LATIN_SIGN4 = 4,
	LATIN_DIGIT = 5,
	LATIN_CAPITAL_LETTER = 6,
    LATIN_SMALL_LETTER = 7,
	LATIN_SUPPLEMENT = 8,
	//CHT
	BOPOMOFO = 9,

	//JPN
	KATAKANA = 10,
	HIRAGANA = 11,
	HIRAGANA_KATAKANA_SOUND_MARK = 12,
	HALF_WIDTH_KATAKANA = 13,

    //KOR
	HANGUL_SYLLABLE = 14,
	HANGUL_COMPATIBILITY_JAMO = 15,
	HALF_WIDTH_HANGUL_1 = 16,
	HALF_WIDTH_HANGUL_2 = 17,
	HALF_WIDTH_HANGUL_3 = 18,
	HALF_WIDTH_HANGUL_4 = 19,
	HALF_WIDTH_HANGUL_5 = 20,

	KANBUN = 21,

    //Common CJK 
	CJK_SYMBOL_AND_PUNCTUATION = 22,
	CJK_HALF_FILL_SPACE = 23,
	CJK_IDEOGRAPH = 24,

	CJK_COMPATIBILITY_IDEOGRAPH = 25,
	CJK_COMPATIBILITY_FORM = 26,

	//SURROGATE section
	SURROGATE = 27,
	HI_SURROGATE = 28,
	LO_SURROGATE = 29,

	//THA
	THAI_CONSONANT = 30,
	THAI_SIGN1 = 31,
	THAI_VOWEL1 = 32,
	THAI_CURRENCY = 33,
	THAI_VOWEL2 = 34,
	THAI_SIGN2 = 35,
	THAI_VOWEL3 = 36,
	THAI_TONE_MARK = 37,
	THAI_SIGN3 = 38,
	THAI_DIGIT = 39,
	THAI_SIGN4 = 40,

	//ARA
	ARA_ISO_8859_6 = 41,
	ARA_POINT_ISO_8859_6 = 42,
	ARA_ARABIC_INDIC_DIGIT = 43, 
	ARA_POINT = 44,
	ARA_EXTENDED = 45,
	ARA_EAST_ARABIC_INDIC_DIGIT = 46,


	//HEB
	HEB_CANTILLATION_MARK = 47,
	HEB_POINT_AND_PUNCTUATION = 48,
	HEB_ISO_8859_8 = 49,
	HEB_YIDDISH_DIGRAPH = 50,
	HEB_ADDITIONAL_PUNCTUATION = 51,
	
	//IND

    //DEVANAGARI
	IND_DEVANAGARI_VARIOUS_SIGN = 52,
	IND_DEVANAGARI_INDEPENDENT_VOWELS = 53,
	IND_DEVANAGARI_CONSONANTS = 54,
	IND_DEVANAGARI_VARIOUS_SIGN2 = 55,
	IND_DEVANAGARI_DEPENDENT_VOWEL_SIGNS = 56,
    IND_DEVANAGARI_VARIOUS_SIGN3 = 57,
    IND_DEVANAGARI_ADDITIONAL_COSONANTS = 58,
    IND_DEVANAGARI_GENERIC_ADDITIONS = 59,
	IND_DEVANAGARI_DEVENAGARI_SPECIFIC_ADDITIONS = 60,

    //TAMIL
    IND_TAMIL_VARIOUS_SIGN = 61,
    IND_TAMIL_INDEPENDENT_VOWELS= 62,
    IND_TAMIL_CONSONANTS=63,
    IND_TAMIL_DEPENDENT_VOWEL_SIGN= 64,
    IND_TAMIL_VARIOUS_SIGN2= 65,
    IND_TAMIL_GENERIC_ADDITIONS= 66,
    IND_TAMIL_TAMIL_SPECIFIC_ADDITIONS= 67,

    //GUJARATI
    IND_GUJARATI_VARIOUS_SIGN= 68,
    IND_GUJARATI_INDEPENDENT_VOWELS= 69,
    IND_GUJARATI_CONSONANTS= 70,
    IND_GUJARATI_VARIOUS_SIGN2= 71,
    IND_GUJARATI_DEPENDENT_VOWEL_SIGNS=72,
    IND_GUJARATI_VARIOUS_SIGN3=73,
    IND_GUJARATI_GENERIC_ADDITIONS=74,

    //TELUGU
    IND_TELUGU_VARIOUS_SIGN=75,
    IND_TELUGU_INDEPENDENT_VOWELS=76,
    IND_TELUGU_CONSONANTS=77,
    IND_TELUGU_DEPENDENT_VOWEL_SIGNS=78,
    IND_TELUGU_VARIOUS_SIGN2=79,
    IND_TELUGU_GENERIC_ADDITIONS=80,

    //KANNADA
    IND_KANNADA_VARIOUS_SIGN=81,
    IND_KANNADA_INDEPENDENT_VOWELS=82,
    IND_KANNADA_CONSONANTS=83,
    IND_KANNADA_DEPENDENT_VOWEL_SIGNS=84,
    IND_KANNADA_VARIOUS_SIGN2=85,
    IND_KANNADA_ADDITIONAL_CONSONANTS=86,
    IND_KANNADA_GENERIC_ADDITIONS=87,

    //GURMUKHI
    IND_GURMUKHI_VARIOUS_SIGN=88,
    IND_GURMUKHI_INDEPENDENT_VOWELS=89,
    IND_GURMUKHI_CONSONANTS=90,
    IND_GURMUKHI_VARIOUS_SIGN2=91,
    IND_GURMUKHI_DEPENDENT_VOWEL_SIGNS=92,
    IND_GURMUKHI_ADDITIONAL_CONSONANTS=93,
    IND_GURMUKHI_GENERIC_ADDITIONS=94,
    IND_GURMUKHI_GURMUKHI_SPECIFIC_ADDITIONS=95,

    




	//RISKY
	RISKY = 96,
	RISKY_DBCS = 97,    //DBCS Specific
	RISKY_SBCS = 98,  //SBCS: 
	RISKY_SBCS_2 = 99, //SBCS:

	//Index
	CPT_SEGMENT_SIZE,
	CPT_SEGMENT_INVALID
};

static WCHAR *g_SegmentDisplayName[] =
{
    //ENG
    L"C0_CONTROL",
	L"LATIN_SIGN1",
	L"LATIN_SIGN2",
	L"LATIN_SIGN3",
	L"LATIN_SIGN4",
	L"LATIN_DIGIT",
	L"LATIN_CAPITAL_LETTER",
    L"LATIN_SMALL_LETTER",
	L"LATIN_SUPPLEMENT",
	//CHT
	L"BOPOMOFO",

	//JPN
	L"KATAKANA",
	L"HIRAGANA",
	L"HIRAGANA_KATAKANA_SOUND_MARK",
	L"HALF_WIDTH_KATAKANA",

    //KOR
	L"HANGUL_SYLLABLE",
	L"HANGUL_COMPATIBILITY_JAMO",
	L"HALF_WIDTH_HANGUL_1",
	L"HALF_WIDTH_HANGUL_2",
	L"HALF_WIDTH_HANGUL_3",
	L"HALF_WIDTH_HANGUL_4",
	L"HALF_WIDTH_HANGUL_5",

	L"KANBUN",

    //Common CJK 
	L"CJK_SYMBOL_AND_PUNCTUATION",
	L"CJK_HALF_FILL_SPACE",
	L"CJK_IDEOGRAPH",

	L"CJK_COMPATIBILITY_IDEOGRAPH",
	L"CJK_COMPATIBILITY_FORM",

	//SURROGATE section
	L"SURROGATE",
	L"HI_SURROGATE",
	L"LO_SURROGATE",

	//THA
	L"THAI_CONSONANT",
	L"THAI_SIGN1",
	L"THAI_VOWEL1",
	L"THAI_CURRENCY",
	L"THAI_VOWEL2",
	L"THAI_SIGN2",
	L"THAI_VOWEL3",
	L"THAI_TONE_MARK",
	L"THAI_SIGN3",
	L"THAI_DIGIT",
	L"THAI_SIGN4",

	//ARA
	L"ARA_ISO_8859_6",
	L"ARA_POINT_ISO_8859_6",
	L"ARA_ARABIC_INDIC_DIGIT",
	L"ARA_POINT",
	L"ARA_EXTENDED",
	L"ARA_EAST_ARABIC_INDIC_DIGIT",


	//HEB
	L"HEB_CANTILLATION_MARK",
	L"HEB_POINT_AND_PUNCTUATION",
	L"HEB_ISO_8859_8",
	L"HEB_YIDDISH_DIGRAPH",
	L"HEB_ADDITIONAL_PUNCTUATION",

    //IND
    //DEVANAGARI
    L"IND_DEVANAGARI_VARIOUS_SIGN",
	L"IND_DEVANAGARI_INDEPENDENT_VOWELS",
	L"IND_DEVANAGARI_CONSONANTS",
	L"IND_DEVANAGARI_VARIOUS_SIGN2",
	L"IND_DEVANAGARI_DEPENDENT_VOWEL_SIGNS",
    L"IND_DEVANAGARI_VARIOUS_SIGN3",
    L"IND_DEVANAGARI_ADDITIONAL_COSONANTS",
    L"IND_DEVANAGARI_GENERIC_ADDITIONS",
	L"IND_DEVANAGARI_DEVENAGARI_SPECIFIC_ADDITIONS",


    //TAMIL
    L"IND_TAMIL_VARIOUS_SIGN",
    L"IND_TAMIL_INDEPENDENT_VOWELS",
    L"IND_TAMIL_CONSONANTS",
    L"IND_TAMIL_DEPENDENT_VOWEL_SIGN",
    L"IND_TAMIL_VARIOUS_SIGN2",
    L"IND_TAMIL_GENERIC_ADDITIONS",
    L"IND_TAMIL_TAMIL_SPECIFIC_ADDITIONS",

    //GUJARATI
    L"IND_GUJARATI_VARIOUS_SIGN",
    L"IND_GUJARATI_INDEPENDENT_VOWELS",
    L"IND_GUJARATI_CONSONANTS",
    L"IND_GUJARATI_VARIOUS_SIGN2",
    L"IND_GUJARATI_DEPENDENT_VOWEL_SIGNS",
    L"IND_GUJARATI_VARIOUS_SIGN3",
    L"IND_GUJARATI_GENERIC_ADDITIONS",

    //TELUGU
    L"IND_TELUGU_VARIOUS_SIGN",
    L"IND_TELUGU_INDEPENDENT_VOWELS",
    L"IND_TELUGU_CONSONANTS",
    L"IND_TELUGU_DEPENDENT_VOWEL_SIGNS",
    L"IND_TELUGU_VARIOUS_SIGN2",
    L"IND_TELUGU_GENERIC_ADDITIONS",

    //KANNADA
    L"IND_KANNADA_VARIOUS_SIGN",
    L"IND_KANNADA_INDEPENDENT_VOWELS",
    L"IND_KANNADA_CONSONANTS",
    L"IND_KANNADA_DEPENDENT_VOWEL_SIGNS",
    L"IND_KANNADA_VARIOUS_SIGN2",
    L"IND_KANNADA_ADDITIONAL_CONSONANTS",
    L"IND_KANNADA_GENERIC_ADDITIONS",

    //GURMUKHI
    L"IND_GURMUKHI_VARIOUS_SIGN",
    L"IND_GURMUKHI_INDEPENDENT_VOWELS",
    L"IND_GURMUKHI_CONSONANTS",
    L"IND_GURMUKHI_VARIOUS_SIGN2",
    L"IND_GURMUKHI_DEPENDENT_VOWEL_SIGNS",
    L"IND_GURMUKHI_ADDITIONAL_CONSONANTS",
    L"IND_GURMUKHI_GENERIC_ADDITIONS",
    L"IND_GURMUKHI_GURMUKHI_SPECIFIC_ADDITIONS",


	//RISK
	L"RISKY",
	L"RISKY_DBCS",    //DBCS Specific
	L"RISKY_SBCS",  //SBCS 
	L"RISKY_SBCS_2", //SBCS

	//Index
	L"CPT_SEGMENT_SIZE",
	L"CPT_SEGMENT_INVALID"
};



//RANGE: 
//Specify the start code and the length of the a code point segment
struct RANGE
{
	DWORD dwStart;
	DWORD dwLength;	
};

// g_cptSegment: 
static const RANGE g_cptSegment[]=
{
	{0x001f,0x005a-0x0000+1}, //C0_CONTROL					  
	{0x0020,0x002f-0x0020+1}, //LATIN_SIGN1,
	{0x003a,0x0040-0x003a+1}, //LATIN_SIGN2,
	{0x005b,0x0060-0x005b+1}, //LATIN_SIGN3,
	{0x007b,0x007f-0x007b+1}, //LATIN_SIGN4,
	{0x0030,0x0039-0x0030+1}, //LATIN_DIGITS,

                              
	
	{0x0041,0x005a-0x0041+1}, //LATIN_CAPITAL_LETTER
    {0x0061,0x007a-0x0061+1}, //LATIN_SMALL_LETTER  
	{0x00c0,0x00ff-0x00c0+1}, //LATIN_SUPPLEMENT


	{0x3105,0x312c-0x3105+1}, //Bopomofo

	{0x30a1,0x30fe-0x30a1+1}, //Katagana
	{0x3041,0x3094-0x3041+1}, //Hiragana
	{0x3099,0x309e-0x3099+1}, //Hiragana+Katagana Sound Mark
	{0xff61,0xff9f-0xff61+1}, //Half width Katagana

	{0xac00,0xd7a3-0xac00+1}, //Hangul Syllables
	{0x3131,0x318e-0x3131+1}, //Hangul Compatibility Jamo
	{0xffa0,0xffbe-0xffa0+1}, //Half width Hangul 1
	{0xffc2,0xffc7-0xffc2+1}, //Half width Hangul 2
	{0xffca,0xffcf-0xffca+1}, //Half width Hangul 3
	{0xffd2,0xffd7-0xffd2+1}, //Half width Hangul 4
	{0xffda,0xffdc-0xffda+1}, //Half width Hangul 5
	

	{0x3190,0x319F-0x3190+1}, //Kanbun

	{0x3000,0x3037-0x3000+1}, //CJK Symbols and Punctuation
	{0x303F,1},				  //IDEOGRAPHIC HALF FILL SPACE
	
	{0x4e00,0x9fff-0x4e00+1}, //CJK Ideographs
	{0xf900,0xfaff-0xf900+1}, //CJK compatiability Ideographs

	{0xfe30,0xfe4f-0xfe30+1}, //CJK compatiability form 

	{0,(0xdbff-0xd800+1)*(0xdfff-0xdc00+1)}, //Surrogate					  //Surrogate 	,
	{0xd800,0xdbff-0xd800+1}, //Hi Surrogate Range
	{0xdc00,0xdfff-0xdc00+1},  //Low Surrogate Range

	{0x0e00,0x0e2e-0x0e00+1}, //THAI_CONSONANTS,
	{0x0e2f,0x0e2f-0x0e2f+1}, //THAI_SIGNS1,
	{0x0e30,0x0e3a-0x0e30+1}, //THAI_VOWELS1,
	{0x0e3f,0x0e3f-0x0e3f+1}, //THAI_CURRENCY,
	{0x0e40,0x0e44-0x0e40+1}, //THAI_VOWELS2,
	{0x0e45,0x0e46-0x0e45+1}, //THAI_SIGNS2,
	{0x0e47,0x0e47-0x0e47+1}, //THAI_VOWELS3,
	{0x0e48,0x0e4b-0x0e48+1}, //THAI_TOME_MARKS,
	{0x0e4c,0x0e4f-0x0e4c+1}, //THAI_SIGNS3,
	{0x0e50,0x0e59-0x0e50+1}, //THAI_DIGITS,
	{0x0e5a,0x0e5b-0x0e5a+1}, //THAI_SIGNS4,

	{0x0600,0x064a-0x0600+1}, //ARA_ISO_8859_6,
	{0x064b,0x065f-0x064b+1}, //ARA_POINTS_ISO_8859_6,
	{0x0660,0x066f-0x0660+1}, //ARA_ARABIC_INDIC_DIGITS,
	{0x0670,0x0670-0x0670+1}, //ARA_POINT,
	{0x0671,0x06ef-0x0671+1}, //ARA_EXTENDED,
	{0x06f0,0x06f9-0x06f0+1}, //ARA_EAST_ARABIC_INDIC_DIGITS,


	{0x0590,0x05af-0x0590+1}, //HEB_CANTILLATION_MARKS,
	{0x05b0,0x05cf-0x05b0+1}, //HEB_POINTS_AND_PUNCTUATION,
	{0x05d0,0x05ef-0x05d0+1}, //HEB_ISO_8859_8,
	{0x05f0,0x05f2-0x05f0+1}, //HEB_YIDDISH_DIGRAPHS,
	{0x05f3,0x05f5-0x05f3+1}, //HEB_ADDITIONAL_PUNCTUATION,

	{0x0900,0x0904-0x0900+1},//IND_DEVANAGARI_VARIOUS_SIGN ,
	{0x0905,0x0914-0x0905+1},//IND_DEVANAGARI_INDEPENDENT_VOWELS ,
	{0x0915,0x0939-0x0915+1},//IND_DEVANAGARI_CONSONANTS ,
	{0x093a,0x093d-0x093a+1},//IND_DEVANAGARI_VARIOUS_SIGN2 ,
	{0x093e,0x094c-0x093e+1},//IND_DEVANAGARI_DEPENDENT_VOWEL_SIGNs,
	{0x094D,0x0957-0x094D+1},//IND_DEVANAGARI_DEVENAGARI_VARIOUS_SIGN3,
    {0x0958,0x095f-0x0958+1},//IND_DEVANAGARI_ADDITIONAL_COSONANTS,
    {0x0960,0x096f-0x0960+1},//IND_DEVANAGARI_GENERIC_ADDITIONS,
    {0x0970,0x0970-0x0970+1},//IND_DEVANAGARI_DEVENAGARI_SPECIFIC_ADDITIONS,



    {0x0b80,0x0b84-0x0b80+1},//IND_TAMIL_VARIOUS_SIGN ,
    {0x0b85,0x0b94-0x0b85+1},//IND_TAMIL_INDEPENDENT_VOWELS,
    {0x0b95,0x0bbd-0x0b95+1},//IND_TAMIL_CONSONANTS,
    {0x0bbe,0x0bcc-0x0bbe+1},//IND_TAMIL_DEPENDENT_VOWEL_SIGN,
    {0x0bcd,0x0bdf-0x0bcd+1},//IND_TAMIL_VARIOUS_SIGN2,
    {0x0be0,0x0bef-0x0be0+1},//IND_TAMIL_GENERIC_ADDITIONS,
    {0x0bf0,0x0bf2-0x0bf0+1},//IND_TAMIL_TAMIL_SPECIFIC_ADDITIONS,


    {0x0a80,0x0a84-0x0a80+1},//IND_GUJARATI_VARIOUS_SIGN,
    {0x0a85,0x0a94-0x0a85+1},//IND_GUJARATI_INDEPENDENT_VOWELS,
    {0x0a95,0x0ab9-0x0a95+1},//IND_GUJARATI_CONSONANTS,
    {0x0aba,0x0abd-0x0aba+1},//IND_GUJARATI_VARIOUS_SIGN2,
    {0x0abe,0x0acc-0x0abe+1},//IND_GUJARATI_DEPENDENT_VOWEL_SIGNS,
    {0x0acd,0x0adf-0x0acd+1},//IND_GUJARATI_VARIOUS_SIGN3,
    {0x0ae0,0x0aef-0x0ae0+1},//IND_GUJARATI_GENERIC_ADDITIONS,


    {0x0c00,0x0c04-0x0c00+1},//IND_TELUGU_VARIOUS_SIGN,
    {0x0c05,0x0c14-0x0c05+1},//IND_TELUGU_INDEPENDENT_VOWELS,
    {0x0c15,0x0c3d-0x0c15+1},//IND_TELUGU_CONSONANTS,
    {0x0c3e,0x0c4c-0x0c3e+1},//IND_TELUGU_DEPENDENT_VOWEL_SIGNS,
    {0x0c4d,0x0c5f-0x0c4d+1},//IND_TELUGU_VARIOUS_SIGN2,
    {0x0c60,0x0c6f-0x0c60+1},//IND_TELUGU_GENERIC_ADDITIONS,

    
    {0x0c80,0x0c84-0x0c80+1},//IND_KANNADA_VARIOUS_SIGN,
    {0x0c85,0x0c94-0x0c85+1},//IND_KANNADA_INDEPENDENT_VOWELS,
    {0x0c95,0x0cbd-0x0c95+1},//IND_KANNADA_CONSONANTS,
    {0x0cbe,0x0ccc-0x0cbe+1},//IND_KANNADA_DEPENDENT_VOWEL_SIGNS,
    {0x0ccd,0x0cd7-0x0ccd+1},//IND_KANNADA_VARIOUS_SIGN2,
    {0x0cd8,0x0cdf-0x0cd8+1},//IND_KANNADA_ADDITIONAL_CONSONANTS,
    {0x0ce0,0x0cef-0x0ce0+1},//IND_KANNADA_GENERIC_ADDITIONS,

    
    {0x0a00,0x0a04-0x0a00+1},//IND_GURMUKHI_VARIOUS_SIGN,
    {0x0a05,0x0a14-0x0a05+1},//IND_GURMUKHI_INDEPENDENT_VOWELS,
    {0x0a15,0x0a39-0x0a15+1},//IND_GURMUKHI_CONSONANTS,
    {0x0a3a,0x0a3d-0x0a3a+1},//IND_GURMUKHI_VARIOUS_SIGN2,
    {0x0a3e,0x0a57-0x0a3e+1},//IND_GURMUKHI_DEPENDENT_VOWEL_SIGNS,
    {0x0a58,0x0a5f-0x0a58+1},//IND_GURMUKHI_ADDITIONAL_CONSONANTS,
    {0x0a60,0x0a6f-0x0a60+1},//IND_GURMUKHI_GENERIC_ADDITIONS,
    {0x0a70,0x0a74-0x0a70+1},//IND_GURMUKHI_GURMUKHI_SPECIFIC_ADDITIONS,



	{0, 1},	//RISK_DBCS
	{0, 1},	//RISK_SBCS
	{0, 1},	//RISK_SBCS_2
	{0, 1},	//CPT_SEGMENT_SIZE,
	{0, 1}  //CPT_SEGMENT_INVALID
};

// Maximum segment of linear piece-wise transform
#define MAX_SEGMENT 64


struct LANG_SEGMENTS
{
	USHORT usLangID;
	CPT_SEGMENT_NAME cptnSegments[MAX_SEGMENT];
};
/*const static LANGID g_SupportedPrimaryLang[] =
{
	LANG_CHINESE,
	LANG_JAPANESE,
	LANG_KOREAN,
	LANG_ENGLISH
}*/

// Maximum number of Language supported
#define MAX_LANGSUPPORTED 15


const static LANG_SEGMENTS g_PrimaryLang[MAX_LANGSUPPORTED] =
{
	{0x804, //SIMPLIFIED CHINESE
		           CJK_IDEOGRAPH,
				   SURROGATE,
				   CPT_SEGMENT_INVALID
	},

	{0x404, //Traditional Chinese
		           CJK_IDEOGRAPH,
				   BOPOMOFO,
				   SURROGATE,
				   CPT_SEGMENT_INVALID
	},


	{0x411, //Japanese
				   HALF_WIDTH_KATAKANA,
				   KATAKANA,
				   HIRAGANA,
				   HIRAGANA_KATAKANA_SOUND_MARK,
				   CJK_IDEOGRAPH,
				   CPT_SEGMENT_INVALID
	},

	{0x412, //Korean
				 HANGUL_SYLLABLE,
				 HANGUL_COMPATIBILITY_JAMO,
	             HALF_WIDTH_HANGUL_1,
	             HALF_WIDTH_HANGUL_2,
	             HALF_WIDTH_HANGUL_3,
	             HALF_WIDTH_HANGUL_4,
	             HALF_WIDTH_HANGUL_5,
				 CJK_IDEOGRAPH,
				 CPT_SEGMENT_INVALID
	},

	{0x409, //English
				   LATIN_CAPITAL_LETTER,
				   LATIN_SMALL_LETTER,
				   CPT_SEGMENT_INVALID
	},

	{0x0407,//GERMAN
				  LATIN_CAPITAL_LETTER,
				  LATIN_SMALL_LETTER,
				  LATIN_SUPPLEMENT,
				  CPT_SEGMENT_INVALID
	},

	{0x41e,//THAI
				THAI_CONSONANT,
				THAI_SIGN1,
				THAI_VOWEL1,
				THAI_CURRENCY,
				THAI_VOWEL2,
				THAI_SIGN2,
				THAI_VOWEL3,
				THAI_TONE_MARK,
				THAI_SIGN3,
				THAI_DIGIT,
				THAI_SIGN4,
				CPT_SEGMENT_INVALID
	},
	{0x401, //ARABIC
					ARA_ISO_8859_6,
					ARA_POINT_ISO_8859_6,
					ARA_ARABIC_INDIC_DIGIT,
					ARA_POINT,
					ARA_EXTENDED,
					ARA_EAST_ARABIC_INDIC_DIGIT,
				    CPT_SEGMENT_INVALID
	},

	{0x40d, //HEBREW
					HEB_CANTILLATION_MARK,
					HEB_POINT_AND_PUNCTUATION,
					HEB_ISO_8859_8,
					HEB_YIDDISH_DIGRAPH,
					HEB_ADDITIONAL_PUNCTUATION,
					CPT_SEGMENT_INVALID
	},

    {0x439,//Hindi
    	            IND_DEVANAGARI_VARIOUS_SIGN,
    	            IND_DEVANAGARI_INDEPENDENT_VOWELS,
	                IND_DEVANAGARI_CONSONANTS,
	                IND_DEVANAGARI_VARIOUS_SIGN2,
	                IND_DEVANAGARI_DEPENDENT_VOWEL_SIGNS,
                    IND_DEVANAGARI_VARIOUS_SIGN3,
                    IND_DEVANAGARI_ADDITIONAL_COSONANTS,
                    IND_DEVANAGARI_GENERIC_ADDITIONS,
	                IND_DEVANAGARI_DEVENAGARI_SPECIFIC_ADDITIONS,
                    CPT_SEGMENT_INVALID
    },
    {0x446,//Punjabi(Gurmukhi)
                    IND_GURMUKHI_VARIOUS_SIGN,
                    IND_GURMUKHI_INDEPENDENT_VOWELS,
                    IND_GURMUKHI_CONSONANTS,
                    IND_GURMUKHI_VARIOUS_SIGN2,
                    IND_GURMUKHI_DEPENDENT_VOWEL_SIGNS,
                    IND_GURMUKHI_ADDITIONAL_CONSONANTS,
                    IND_GURMUKHI_GENERIC_ADDITIONS,
                    IND_GURMUKHI_GURMUKHI_SPECIFIC_ADDITIONS,
                    CPT_SEGMENT_INVALID
    },
    {0x447,//Gujarati
                    IND_GUJARATI_VARIOUS_SIGN,
                    IND_GUJARATI_INDEPENDENT_VOWELS,
                    IND_GUJARATI_CONSONANTS,
                    IND_GUJARATI_VARIOUS_SIGN2,
                    IND_GUJARATI_DEPENDENT_VOWEL_SIGNS,
                    IND_GUJARATI_VARIOUS_SIGN3,
                    IND_GUJARATI_GENERIC_ADDITIONS,
                    CPT_SEGMENT_INVALID
    },
    {0x449,//Tamil
                    IND_TAMIL_VARIOUS_SIGN,
                    IND_TAMIL_INDEPENDENT_VOWELS,
                    IND_TAMIL_CONSONANTS,
                    IND_TAMIL_DEPENDENT_VOWEL_SIGN,
                    IND_TAMIL_VARIOUS_SIGN2,
                    IND_TAMIL_GENERIC_ADDITIONS,
                    IND_TAMIL_TAMIL_SPECIFIC_ADDITIONS,
                    CPT_SEGMENT_INVALID
    },
    {0x44a,//Telugu
                    IND_TELUGU_VARIOUS_SIGN,
                    IND_TELUGU_INDEPENDENT_VOWELS,
                    IND_TELUGU_CONSONANTS,
                    IND_TELUGU_DEPENDENT_VOWEL_SIGNS,
                    IND_TELUGU_VARIOUS_SIGN2,
                    IND_TELUGU_GENERIC_ADDITIONS,
                    CPT_SEGMENT_INVALID
    },
    {0x44b,//Kannada
                    IND_KANNADA_VARIOUS_SIGN,
                    IND_KANNADA_INDEPENDENT_VOWELS,
                    IND_KANNADA_CONSONANTS,
                    IND_KANNADA_DEPENDENT_VOWEL_SIGNS,
                    IND_KANNADA_VARIOUS_SIGN2,
                    IND_KANNADA_ADDITIONAL_CONSONANTS,
                    IND_KANNADA_GENERIC_ADDITIONS,
                    CPT_SEGMENT_INVALID
    }



};

/*const static LANG_SEGMENTS g_SubLang[] =
{
	{SUBLANG_CHINESE_TRADITIONAL,BOPOMOFO, CPT_SEGMENT_INVALID},

};*/



//Risk Character related data

#define SIZE_G_TRAILBYTE 27
#define SIZE_G_LEADBYTE 5
const static unsigned char g_LeadByte[SIZE_G_LEADBYTE] = {
	0x81,
    0x82,
	0x9f,
	0xef,
	0xfc,
};
const static unsigned char g_TrailByte[SIZE_G_TRAILBYTE] = {
    '[',
    ']',
    '|',
    0xA1,  //inverted ! mark
    0xAE,  //Registered Sign
    0xBF,  //inverted ? mark
    0xDF,  //Latin small letter sharp S
    0xE0,  //Latin small letter with Grave
    0x40,  //@
    0xFC,  //Latin small letter u with Diaeresis
    0x20,  //space
    '\\',
    '/',
    ':',
    '<',
    '>',
    '|',
    '.',
    '_',
    '*',
    '+',
    ',',
    '?',
    '"',
    'a',  // in lower case alphabate range
    'A',  // in higher case alphabate range 
    0x00
};

const WCHAR InvalidCharNetBios[50] = {
    0x0020,
    L'\\',
    L'/',
    L':',
    L'<',
    L'>',
    L'|',
    L'.',
    L'_',
    L'*',
    L'+',
    L',',
    L'?',
    L'"',
    0x0000
};

#endif 